language: node_js
node_js:
  - 4
  - 6
  - 8
cache:
  directories:
    - node_modules
sudo: false
before_install:
  - npm install -g npm@5
script:
  - npm run lint
  - MOCHA_OPTIONS=--forbid-only npm test
# Acceptance tests failed but didn't break the build
# after_success:
#   - npm run coveralls
#   - cd accept && ./install.sh && source .profile && ./run
jobs:
  include:
    # stage: test runs automatically first
    - stage: npm release
      script: echo "Deploying to npm..."
      node_js: 8
      # release only main versions, not prereleases
      if: tag =~ ^v\d+\.\d+\.\d+$
      deploy:
        provider: npm
        email: engineering+npm@particle.io
        api_key:
          secure: i7cDtd0yXKPTHGY+IQG7m9Qlf5CkHkb2JNZm5n4RjsmR1uS5KKGQcl57oQNPAx0rWqNXhQEZYOOrM3xVBqf8tyH15tMSGQUYv22RMr2stpASfuv57M17xBrXgjbWnZwA+Ftztbk8Z9N2v/z/z2mWWcvg2NMUNz15oDeggbVLel92fxX23fKMwfyXkYv4Qc4APo0B7hx1A6DIkm6RIoizet/VPB8DWyZvBYXUM9YgkZdPPhj2EX24pS4dTIhCWlKsNz1WuH3aQZ/sdkCkqXpDlT8QUbzY2swlGYQXFmw6w9wpeG64WfPk3A4cA2dQ/j1KiLjaPS7n7qqH+aHexsy9x6QzvtiOwcUV4QUhnxpQ2kgR9up02onvnCL35Ed0c+de9r/zjdT/uvjvQvIc4Csg0Nx9UIb1Cu5fHEbmQIX+GF9aa6TGswxA22cPy3EkEwbNdhY0zfI3WC8+r6Yut8tLfRrFH8pGCkTs2i24GY7j1kLbDQkJi8MfuXHApCWCz68T2EHOc6d4dfotUjSgg3Ahb7R2cxSic7AAJh4BVd6zXX4pxC4OcmE5mmFbga2eY/1/tIlQpfyNAb9hCwSHB52hrWrS1SdiPDgAdNenpAw66dvYxt12p/UMsR6XO2wiEJmL+5yeG0nVwrxMCghZCfMZJEOxbu5I1rT2R96W7bpg5c0=
        skip_cleanup: true
        on:
          tags: true
notifications:
  slack:
    secure: D1UYT6DvXsvRhzYVOwPDNeVPmq19jAx8QMmAR7b2uAF1+coQNn/CIToKIjgdnlaEPCKElNG4MqxYg4v3BFA5r+gXsHE6lBsKtZFJk1OAQ8hiL1At6pNxOFNlR+P3lmH9N+Y7hKQNxi5MHP+qTV9GE/we/1oMyoGoBEVEmT7I/YndCcdQihQVhFnvBkVdOfyFUIwJBwlNyFa29WT9da282wouli74f0pbU/pKl7hQwCld6/76gW0nnQ2ZrsQqyk8RYKVI8tcGw0BzgmFR9xYvg94uKJ2dy9Dt2aYwq6pHtYyXPhEKNzMDGB4IpJynEPXPId7GrxIAIZu68IWUuG6Im1kqfm2wk9P4TIZECensqcRG2STdlPzt+b9UJF6DsmlL4Xfrn7ZZEppP8mni7uAI1WjNa/WMJ09VsMQ0Rpd6SPfDPR37d0TqhOefq01OI5wOBTsimLycx6cq8JIYG03FAZ/UzaFnvOlmsLI322u1dSsmbYpgjch62n+J27gAgHsn5rk4H3h9LDeutixQtZWClHDS27BRbllinhifdfC6NqseDAsF9tH1oOhR493unfPEjRy0O0bxSpvP1mK8Sfqz9UdtGjeIDyMylXiNtzfiKpsXtEomvltQFToF+LnDXCjyH7lUN/HAkZQiOA24INUmKUZHufectio63rVds9xX/2E=
